### ISSUE TITLE
Research alternative Markdown editor libraries

### ISSUE THREAD

**Issue by FSM1** [ChainSafe/ui-monorepo#1007]
- Reseach on suitable code plugins to use for a markdown editor

Definition of done: A specific tool/set of tools to use to allow the user to edit markdown files (only on their own drive), with no collaboration.

Bonus points:
Investigate collaborative editing possibilities (CRDTs) that we could use, once we decide to enable collaborative editing.

Potential alternatives to investigate:

https://quilljs.com/
https://etherpad.org/ & https://github.com/audreyt/ethercalc

**Comment by Tbaut** [comment]
closing as this is not something we'll work on in the short term.
