### ISSUE TITLE
Implement Purchase page

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/ui-monorepo#1075]
This should be a `/purchase` route showing all the plans than we have.
This component is already implemented `packages/files-ui/src/Components/Modules/Settings/PurchasePlan/index.tsx`

It'll need to be adapted to the new design

![image](https://user-images.githubusercontent.com/12774278/122255306-49b33c00-cece-11eb-8d40-bbfec364ed94.png)

- API to provide a list of all the plans and plan details
- UI to send CC details to Stripe in exchange for a Token
- Token to be provided to API for verification.

**Comment by FSM1** [comment]
Duplicate of #1184
