### ISSUE TITLE
UI Tests: Find a way to deal with links that open in tabs (cypress)

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/ui-monorepo#1084]
We have a "send feedback" button on the left hand navigation bar that navigates to block survey in another tab when it's clicked. 

Cypress doesn't support browser tabs so I need to research and look for an alternative way to assure the send feedback button works as intended.

**Comment by asnaith** [comment]
I took a quick peek at this today whilst waiting on something else and was going to do it the recommended way.

Oddly there is no `a` or `href` attributes visible in the DOM for this element yet it works. Seems like the anchor might be getting obscured somehow. 

<img width="923" alt="Screen Shot 2021-07-19 at 4 19 54 PM" src="https://user-images.githubusercontent.com/3982665/126239665-c18b157c-238f-4201-b7db-200f0492a800.png">

**Comment by FSM1** [comment]
ahhh that redirect is handled in the button `onClick` handler is dealing with that. 

I honestly think this is a minor enough issue to just close.

**Comment by asnaith** [comment]
@FSM1 Agreed, I'm ok with that. It wouldn't be a "critical path" test so think it's ok not to make it part of the automation test suite especially if it requires extra work to make it testable.
